// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYn-B8hooaEEBvNn9P7i_TNUHh9ZYgGnQ',
    appId: '1:381264833820:web:7a8b917a3100fbadcfded9',
    messagingSenderId: '381264833820',
    projectId: 'nibserve',
    authDomain: 'nibserve.firebaseapp.com',
    storageBucket: 'nibserve.firebasestorage.app',
    measurementId: 'G-41N2F9L1KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgzO7HAgPEykbEzh0AYMJ-S7x45LoxLQ',
    appId: '1:381264833820:android:fac2c006bccd606dcfded9',
    messagingSenderId: '381264833820',
    projectId: 'nibserve',
    storageBucket: 'nibserve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUYOTUKxbQdzclEKQGjhVCDN9vn9qahM',
    appId: '1:381264833820:ios:d2d7fc3e68815af3cfded9',
    messagingSenderId: '381264833820',
    projectId: 'nibserve',
    storageBucket: 'nibserve.firebasestorage.app',
    iosClientId: '381264833820-hl253d1095jmth7pv4jh2dgo7d0a91qs.apps.googleusercontent.com',
    iosBundleId: 'com.nibnox.nibserveDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUYOTUKxbQdzclEKQGjhVCDN9vn9qahM',
    appId: '1:381264833820:ios:d2d7fc3e68815af3cfded9',
    messagingSenderId: '381264833820',
    projectId: 'nibserve',
    storageBucket: 'nibserve.firebasestorage.app',
    iosClientId: '381264833820-hl253d1095jmth7pv4jh2dgo7d0a91qs.apps.googleusercontent.com',
    iosBundleId: 'com.nibnox.nibserveDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYn-B8hooaEEBvNn9P7i_TNUHh9ZYgGnQ',
    appId: '1:381264833820:web:235e317402b03e3acfded9',
    messagingSenderId: '381264833820',
    projectId: 'nibserve',
    authDomain: 'nibserve.firebaseapp.com',
    storageBucket: 'nibserve.firebasestorage.app',
    measurementId: 'G-1H8Z9PH4DB',
  );
}
